package com.products.productservice.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.ManyToOne;
import lombok.Data;

import java.lang.reflect.Type;

/**
 * Entity class representing a log entry for AI content generation.
 * This class is used to track the input prompts and output responses
 * generated by AI services (e.g., Azure OpenAI, DALL·E) for a specific product.
 */
@Entity
@Data
public class AIGenerationLog extends BaseModel {

    /**
     * The ID of the product associated with this AI generation log.
     */
    private Long productId;

    /**
     * The type of AI generation (e.g., description generation, image generation).
     * This is a many-to-one relationship with the AIGenerationType entity.
     */
    @ManyToOne
    private AIGenerationType type;

    /**
     * The input prompt sent to the AI service for generating content.
     * This field can store up to 2000 characters.
     */
    @Column(length = 2000)
    private String inputPrompt;

    /**
     * The output response received from the AI service.
     * This field can store up to 2000 characters.
     */
    @Column(length = 2000)
    private String outputResponse;

}